import { TrackDefinition, LevelItem, ModuleItem, LessonItem, QuizItem } from '@/types/curriculum';

// Helper to generate a standardized module with lessons and quiz
function createSpecModule(params: {
  id: string;
  num: string;
  icon: string;
  gradient: string;
  titleAr: string;
  titleEn: string;
  titleFr: string;
  descAr: string;
  descEn: string;
  descFr: string;
  trainerAr: string;
  trainerEn: string;
  trainerFr: string;
  videoId?: string;
  quizQuestionAr: string;
  quizOptionsAr: string[];
  quizAns: number;
  quizExplanationAr: string;
}): ModuleItem {
  const lesson1: LessonItem = {
    id: `${params.id}_l1`,
    type: 'video',
    title: {
      ar: `الدرس 01: الإطار المفاهيمي والتطبيقي لـ ${params.titleAr}`,
      en: `Lesson 01: Conceptual Framework of ${params.titleEn}`,
      fr: `Leçon 01: Cadre Conceptuel de ${params.titleFr}`,
    },
    instructor: { ar: params.trainerAr, en: params.trainerEn, fr: params.trainerFr },
    duration: { ar: '20 دقيقة', en: '20 mins', fr: '20 mins' },
    img: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=600&q=80',
    desc: {
      ar: `استيعاب المفاهيم الأساسية، المعايير المعتمدة، وخارطة التطبيق العملي لمقياس ${params.titleAr}.`,
      en: `Mastering foundational concepts and practical implementation blueprints for ${params.titleEn}.`,
      fr: `Maîtriser les concepts et la mise en œuvre pratique de ${params.titleFr}.`,
    },
    video_id: params.videoId || 'dQw4w9WgXcQ',
  };

  const lesson2: LessonItem = {
    id: `${params.id}_l2`,
    type: 'doc',
    title: {
      ar: `الدرس 02: دراسة حالة وتطبيقات ميدانية لـ ${params.titleAr}`,
      en: `Lesson 02: Case Studies & Field Applications for ${params.titleEn}`,
      fr: `Leçon 02: Études de Cas et Applications de ${params.titleFr}`,
    },
    instructor: { ar: params.trainerAr, en: params.trainerEn, fr: params.trainerFr },
    duration: { ar: '25 دقيقة', en: '25 mins', fr: '25 mins' },
    img: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=600&q=80',
    desc: {
      ar: `تحليل نماذج عملية واقعية واستخلاص أفضل الممارسات والأخطاء الشائعة في التطبيق.`,
      en: `Real-world case analysis, extracting best practices and avoiding common execution pitfalls.`,
      fr: `Analyse de cas réels, bonnes pratiques et pièges à éviter.`,
    },
    video_id: params.videoId || 'dQw4w9WgXcQ',
  };

  const quiz: QuizItem = {
    id: `quiz_${params.id}`,
    title: {
      ar: `اختبار تقييم مقياس ${params.titleAr}`,
      en: `Assessment Quiz for ${params.titleEn}`,
      fr: `Quiz d'Évaluation de ${params.titleFr}`,
    },
    passingScore: 70,
    timeLimitSeconds: 120,
    questions: [
      {
        q: params.quizQuestionAr,
        options: params.quizOptionsAr,
        ans: params.quizAns,
        explanation: params.quizExplanationAr,
      },
      {
        q: `ما هو المعيار الأهم لضمان نجاح واستدامة تطبيق ${params.titleAr} في بيئة العمل التدريبية؟`,
        options: [
          'الاعتماد على النظريات المجردة دون مواءمة واقعية',
          'المواءمة المستمرة مع الأهداف الاستراتيجية وقياس الأثر العملي',
          'تجاهل تقييمات وتغذية المتدربين الراجعة',
          'التنفيذ السريع بدون خطة أو مؤشرات أداء',
        ],
        ans: 1,
        explanation: 'الاستدامة تتطلب ربط المخرجات بالأهداف الميدانية الملموسة والقياس المستمر للأثر.',
      },
    ],
  };

  return {
    id: params.id,
    num: params.num,
    icon: params.icon,
    gradient: params.gradient,
    moduleLabel: { ar: `مقياس ${params.num}`, en: `Module ${params.num}`, fr: `Module ${params.num}` },
    title: { ar: params.titleAr, en: params.titleEn, fr: params.titleFr },
    desc: { ar: params.descAr, en: params.descEn, fr: params.descFr },
    summary: {
      ar: `يهدف هذا المقياس إلى بناء كفاءة نوعية ورصينة في ${params.titleAr} مع تطبيقات وحقائب عملية متكاملة.`,
      en: `This module develops rigorous competence in ${params.titleEn} with complete hands-on frameworks.`,
      fr: `Ce module vise à développer une compétence solide en ${params.titleFr}.`,
    },
    interviewQuestion: {
      ar: `كيف توظف مبادئ ${params.titleAr} في حل معضلة تدريبية معقدة تواجه مؤسستك؟`,
      en: `How do you apply principles of ${params.titleEn} to resolve complex organizational training challenges?`,
      fr: `Comment appliquez-vous les principes de ${params.titleFr} pour résoudre un défi complexe?`,
    },
    lessons: [lesson1, lesson2],
    quiz,
  };
}

// ------------------------------------------------------------------------------------------------
// 2. Track: Tech AI (AIT101) - Generative AI for Trainers
// ------------------------------------------------------------------------------------------------
export function buildTechAiTrack(): TrackDefinition {
  const fndModules: ModuleItem[] = [
    createSpecModule({
      id: 'ai_mod_01',
      num: '01',
      icon: '🤖',
      gradient: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
      titleAr: 'مفاهيم الذكاء الاصطناعي التوليدي وهندسة الأوامر',
      titleEn: 'Generative AI Concepts & Prompt Engineering',
      titleFr: "Concepts de l'IA Générative et Prompt Engineering",
      descAr: 'فهم البنية التحتية للنماذج اللغوية وصياغة الأوامر الدقيقة لإنتاج المحتوى المعرفي.',
      descEn: 'Understanding LLM architecture and crafting precision prompts for knowledge creation.',
      descFr: 'Comprendre les LLM et rédiger des prompts précis pour la création de contenu.',
      trainerAr: 'كريم زروقي',
      trainerEn: 'Karim Zerrougui',
      trainerFr: 'Karim Zerrougui',
      quizQuestionAr: 'ما هي التقنية الأكثر فعالية لتحسين دقة استجابات النماذج اللغوية الكبيرة؟',
      quizOptionsAr: [
        'إعطاء أوامر غامضة ومقتضبة',
        'تحديد الدور، السياق، المهمة، والشكل المطلوب بدقة (Role, Context, Task, Format)',
        'تكرار نفس الكلمة عدة مرات',
        'عدم تقديم أي أمثلة سياقية',
      ],
      quizAns: 1,
      quizExplanationAr: 'تأطير الدور والسياق والمخرجات المستهدفة يقلل الهلوسة ويضمن مخرجات تدريبية عالية الدقة.',
    }),
    createSpecModule({
      id: 'ai_mod_02',
      num: '02',
      icon: '📚',
      gradient: 'linear-gradient(135deg, #2563eb, #38bdf8)',
      titleAr: 'هندسة وتطوير الحقائب التدريبية بالذكاء الاصطناعي',
      titleEn: 'AI-Powered Courseware & Curriculum Engineering',
      titleFr: "Ingénierie des Cours et Supports avec l'IA",
      descAr: 'استخدام وكلاء الذكاء الاصطناعي لبناء الأهداف، خطط الدروس، والتمارين التفاعلية في دقائق.',
      descEn: 'Using AI agents to structure learning outcomes, lesson plans, and interactive exercises in minutes.',
      descFr: 'Utiliser les agents IA pour structurer les objectifs pédagogiques et exercices interactifs.',
      trainerAr: 'نور الهدى صالحي',
      trainerEn: 'Nour El Houda Salhi',
      trainerFr: 'Nour El Houda Salhi',
      quizQuestionAr: 'كيف يساهم الذكاء الاصطناعي في تسريع إعداد الحقائب التدريبية؟',
      quizOptionsAr: [
        'عبر إلغاء دور المدرب البشري تماماً',
        'عبر توليد المسودات الأولية، خطط الدروس، والأنشطة بناءً على أهداف محددة',
        'بنسخ مقالات الإنترنت دون تعديل',
        'بزيادة التعقيد الإداري',
      ],
      quizAns: 1,
      quizExplanationAr: 'الذكاء الاصطناعي يعمل كمساعد بحثي وبنائي سريع يترك للمدرب مهمة التحكيم والتجويد البشري.',
    }),
    createSpecModule({
      id: 'ai_mod_03',
      num: '03',
      icon: '📊',
      gradient: 'linear-gradient(135deg, #0284c7, #06b6d4)',
      titleAr: 'توليد العروض التقديمية والشرائح الذكية وتصميم السيناريوهات',
      titleEn: 'AI Slide Generation & Interactive Scenario Design',
      titleFr: "Génération de Diapositives et Scénarios Interactifs",
      descAr: 'توظيف أدوات الشرائح الآلية والتحويل الفوري من نص خام إلى شرائح احترافية.',
      descEn: 'Converting raw concepts into interactive visual slides and case scenarios seamlessly.',
      descFr: 'Transformer des concepts bruts en diapositives professionnelles et scénarios interactifs.',
      trainerAr: 'عادل بلحاج',
      trainerEn: 'Adel Belhadj',
      trainerFr: 'Adel Belhadj',
      quizQuestionAr: 'ما الميزة الأساسية لاستخدام أدوات توليد الشرائح بالذكاء الاصطناعي؟',
      quizOptionsAr: [
        'عدم الحاجة لأي محتوى مسبق',
        'توفير ساعات التصميم اليدوي مع الحفاظ على التناسق البصري للهوية',
        'منع استخدام الصور في العرض',
        'جعل الشرائح غير قابلة للتعديل',
      ],
      quizAns: 1,
      quizExplanationAr: 'الأدوات الذكية ترتب الهيكل البصري بسرعة فائقة وتمكن المدرب من التركيز على الرسالة.',
    }),
    createSpecModule({
      id: 'ai_mod_04',
      num: '04',
      icon: '🎨',
      gradient: 'linear-gradient(135deg, #7c3aed, #ec4899)',
      titleAr: 'توليد وتعديل الصور التعليمية والمخططات التوضيحية',
      titleEn: 'Educational Image Generation & Diagram Synthesis',
      titleFr: "Génération d'Images Éducatives et Synthèse de Schémas",
      descAr: 'إنتاج رسوم توضيحية ومخططات ذهنية مخصصة تخدم الشرح وتكسر جمود النصوص.',
      descEn: 'Creating custom visual assets, mind maps, and diagrams to amplify comprehension.',
      descFr: "Création d'illustrations et cartes mentales pour amplifier la compréhension.",
      trainerAr: 'إيمان تواتي',
      trainerEn: 'Imane Touati',
      trainerFr: 'Imane Touati',
      quizQuestionAr: 'ما أهمية الصور التوضيحية المولدة بالذكاء الاصطناعي في التعليم؟',
      quizOptionsAr: [
        'لأغراض التزيين فقط دون ارتباط بالموضوع',
        'تجسيد المفاهيم المعقدة والمجردة في وسائط بصرية ترفع معدل الاستيعاب',
        'استبدال النص المكتوب بالكامل',
        'زيادة حجم الملف فقط',
      ],
      quizAns: 1,
      quizExplanationAr: 'التجسيد البصري يرفع معدل استبقاء المعلومة في ذاكرة المتدرب بنسبة تتجاوز 65%.',
    }),
    createSpecModule({
      id: 'ai_mod_05',
      num: '05',
      icon: '⚖️',
      gradient: 'linear-gradient(135deg, #d97706, #f59e0b)',
      titleAr: 'أخلاقيات الذكاء الاصطناعي، الخصوصية، ومكافحة الانتحال',
      titleEn: 'AI Ethics, Data Privacy & Anti-Plagiarism',
      titleFr: "Éthique de l'IA, Confidentialité et Anti-Plagiat",
      descAr: 'حماية بيانات المتدربين، التحقق من الموثوقية الأكاديمية، والامتثال للتشريعات.',
      descEn: 'Safeguarding user privacy, ensuring academic integrity, and avoiding algorithmic bias.',
      descFr: 'Protection de la vie privée, intégrité académique et évitement des biais algorithmiques.',
      trainerAr: 'كريم زروقي',
      trainerEn: 'Karim Zerrougui',
      trainerFr: 'Karim Zerrougui',
      quizQuestionAr: 'ما هو الإجراء الأمني الأهم عند استخدام أدوات الذكاء الاصطناعي مع بيانات المتدربين؟',
      quizOptionsAr: [
        'مشاركة كافة المعلومات الحساسة دون تشفير',
        'إخفاء الهوية وتجنب رفع أي بيانات شخصية أو سرية دون إذن صريح وسياسة خصوصية',
        'استخدام كلمات مرور بسيطة',
        'عدم قراءة شروط الاستخدام للمنصة',
      ],
      quizAns: 1,
      quizExplanationAr: 'حماية خصوصية المتدربين والبيانات المؤسسية هي التزام قانوني وأخلاقي أساسي.',
    }),
    createSpecModule({
      id: 'ai_mod_06',
      num: '06',
      icon: '⚡',
      gradient: 'linear-gradient(135deg, #059669, #10b981)',
      titleAr: 'أتمتة المهام الروتينية للمدرب وربط أدوات الإنتاجية',
      titleEn: 'Trainer Task Automation & Productivity Integration',
      titleFr: 'Automatisation des Tâches et Outils de Productivité',
      descAr: 'ربط بريد المدرب، الجداول، المتابعات، وإرسال الشهادات آلياً عبر أدوات الأتمتة.',
      descEn: 'Connecting emails, schedules, follow-ups, and certificates through no-code automations.',
      descFr: 'Automatiser la messagerie, les plannings et les attestations via des flux automatisés.',
      trainerAr: 'عادل بلحاج',
      trainerEn: 'Adel Belhadj',
      trainerFr: 'Adel Belhadj',
      quizQuestionAr: 'كيف تساهم أتمتة مهام التدريب في رفع جودة العملية التعليمية؟',
      quizOptionsAr: [
        'بتقليل وقت التواصل مع المتدربين',
        'بتحرير وقت المدرب من الأعباء الروتينية للتفرغ للتيسير والارتقاء بالتفاعل البشري',
        'بإلغاء التقييم المباشر',
        'بإيقاف التواصل عبر البريد الإلكتروني',
      ],
      quizAns: 1,
      quizExplanationAr: 'الأتمتة توفر ما يصل إلى 40% من وقت المدرب ليوجهه نحو التدريب الإنساني النوعي.',
    }),
    createSpecModule({
      id: 'ai_mod_07',
      num: '07',
      icon: '🧠',
      gradient: 'linear-gradient(135deg, #4338ca, #6366f1)',
      titleAr: 'أساسيات التعلم الآلي وفهم خوارزميات التوصية',
      titleEn: 'Machine Learning Fundamentals & Recommendation Systems',
      titleFr: "Bases du Machine Learning et Systèmes de Recommandation",
      descAr: 'كيف تفهم الأنظمة الذكية تفضيلات المتدربين وتقدم مسارات تعلم متكيفة ومخصصة.',
      descEn: 'How intelligent engines analyze learner behavior to offer adaptive learning journeys.',
      descFr: 'Comprendre comment les algorithmes analysent le comportement pour adapter les parcours.',
      trainerAr: 'نور الهدى صالحي',
      trainerEn: 'Nour El Houda Salhi',
      trainerFr: 'Nour El Houda Salhi',
      quizQuestionAr: 'ما هو نظام التعلم التكيفي (Adaptive Learning)؟',
      quizOptionsAr: [
        'نظام يقدم نفس المحتوى لكل المتدربين بنفس الوتيرة إجبارياً',
        'نظام يضبط سرعة وصعوبة المحتوى ديناميكياً وفق أداء واحتياج كل متدرب',
        'نظام يمنع المتدرب من طرح الأسئلة',
        'نظام تقليدي ورقي فقط',
      ],
      quizAns: 1,
      quizExplanationAr: 'التعلم التكيفي يخصص المسار التعليمي لرفع معدل الإتقان ومعالجة الفجوات الفردية.',
    }),
    createSpecModule({
      id: 'ai_mod_08',
      num: '08',
      icon: '🎯',
      gradient: 'linear-gradient(135deg, #be123c, #f43f5e)',
      titleAr: 'تطبيقات الذكاء الاصطناعي اليومية في إدارة القاعات التدريبية',
      titleEn: 'Everyday AI Applications in Classroom Management',
      titleFr: "Applications Quotidiennes de l'IA en Salle de Formation",
      descAr: 'التلخيص الفوري للمناقشات، إدارة الأسئلة الشائعة، وقياس تفاعل المشاركين لحظياً.',
      descEn: 'Real-time discussion summarization, live Q&A moderation, and participant engagement tracking.',
      descFr: 'Synthèse en temps réel des discussions et suivi de l’engagement des participants.',
      trainerAr: 'إيمان تواتي',
      trainerEn: 'Imane Touati',
      trainerFr: 'Imane Touati',
      quizQuestionAr: 'ما هي الفائدة الكبرى للتلخيص الذكي للنقاشات أثناء الورشة التدريبية؟',
      quizOptionsAr: [
        'إلغاء التفاعل الشفهي',
        'توثيق المخرجات والأفكار الجماعية فورياً وتقديم خلاصة مركّزة بنهاية الجلسة',
        'منع المتدربين من التعبير عن آرائهم',
        'تأخير انتهاء الورشة',
      ],
      quizAns: 1,
      quizExplanationAr: 'التلخيص الفوري يحفظ المعرفة الجماعية الناتجة من العصف الذهني دون جهد توثيقي مفرط.',
    }),
  ];

  const empModules: ModuleItem[] = [
    createSpecModule({
      id: 'ai_mod_09',
      num: '09',
      icon: '🔬',
      gradient: 'linear-gradient(135deg, #1e1b4b, #4338ca)',
      titleAr: 'الأوامر المتقدمة وهندسة سلاسل التفكير (Chain of Thought)',
      titleEn: 'Advanced Prompting & Chain-of-Thought Reasoning',
      titleFr: 'Prompts Avancés et Raisonnement Pas à Pas',
      descAr: 'توجيه النماذج للتحليل المنطقي متعدد المراحل وحل المشكلات الاستراتيجية المعقدة.',
      descEn: 'Directing models through multi-step logical reasoning to solve complex challenges.',
      descFr: 'Guider les modèles à travers un raisonnement logique en plusieurs étapes.',
      trainerAr: 'كريم زروقي',
      trainerEn: 'Karim Zerrougui',
      trainerFr: 'Karim Zerrougui',
      quizQuestionAr: 'ما الذي تحققه تقنية Chain-of-Thought (سلسلة التفكير)؟',
      quizOptionsAr: [
        'تجعل النموذج يعطي إجابة عشوائية',
        'تلزم النموذج بتفكيك المشكلة إلى خطوات منطقية متسلسلة قبل الوصول للحل النهائي',
        'تقلل سرعة الاتصال بالإنترنت',
        'تحذف البيانات السابقة',
      ],
      quizAns: 1,
      quizExplanationAr: 'سلسلة التفكير ترفع دقة الحلول في الرياضيات والمنطق والتخطيط الاستراتيجي بدرجة هائلة.',
    }),
    createSpecModule({
      id: 'ai_mod_10',
      num: '10',
      icon: '🔌',
      gradient: 'linear-gradient(135deg, #0f172a, #334155)',
      titleAr: 'دمج واجهات البرمجة التطبيقية (APIs) في المنصات التعليمية',
      titleEn: 'AI API Integrations in Learning Management Systems',
      titleFr: "Intégration d'API IA dans les Plateformes LMS",
      descAr: 'توصيل خدمات الذكاء الاصطناعي بموقع الأكاديمية وربط بوتات الدردشة الذكية لخدمة المتدربين.',
      descEn: 'Connecting AI endpoints to LMS platforms and deploying dedicated learner chatbots.',
      descFr: 'Connecter des API IA aux plateformes LMS et déployer des chatbots dédiés.',
      trainerAr: 'عادل بلحاج',
      trainerEn: 'Adel Belhadj',
      trainerFr: 'Adel Belhadj',
      quizQuestionAr: 'ما هي وظيفة الـ API عند ربط الذكاء الاصطناعي بمنصة التدريب؟',
      quizOptionsAr: [
        'إنشاء قاعدة بيانات فارغة',
        'تمكين المنصة من إرسال طلبات للنموذج الذكي واستقبال النتائج برمجياً وبشكل فوري',
        'إلغاء اشتراك المنصة',
        'تشفير الصور فقط',
      ],
      quizAns: 1,
      quizExplanationAr: 'واجهات الـ API تسمح بتضمين قوة النماذج اللغوية داخل تجربة المتدرب في المنصة مباشرة.',
    }),
  ];

  const conModules: ModuleItem[] = [
    createSpecModule({
      id: 'ai_mod_17',
      num: '17',
      icon: '👑',
      gradient: 'linear-gradient(135deg, #701a75, #a21caf)',
      titleAr: 'بناء وكلاء الذكاء الاصطناعي المستقلين (Autonomous AI Agents)',
      titleEn: 'Architecting Autonomous AI Agents for Learning Organizations',
      titleFr: "Architecturer des Agents IA Autonomes pour la Formation",
      descAr: 'تصميم وكلاء قادرين على التخطيط، البحث، التنفيذ، وتصحيح المهام الذاتية للأكاديمية.',
      descEn: 'Designing multi-agent frameworks capable of self-directed research, grading, and execution.',
      descFr: 'Concevoir des agents capables de recherche, correction et exécution autonomes.',
      trainerAr: 'كريم زروقي',
      trainerEn: 'Karim Zerrougui',
      trainerFr: 'Karim Zerrougui',
      quizQuestionAr: 'ما الذي يميز وكيل الذكاء الاصطناعي (AI Agent) عن المحادثة العادية (Chatbot)؟',
      quizOptionsAr: [
        'الوكيل يمتلك قدرة على التخطيط المستقل واستخدام الأدوات الخارجية وإتمام مهام متعددة الخطوات',
        'الوكيل لا يستطيع الرد على الأسئلة',
        'الوكيل مجرد واجهة رسومية فقط',
        'الوكيل يعمل بدون نماذج لغوية',
      ],
      quizAns: 0,
      quizExplanationAr: 'الوكلاء يملكون الاستقلالية واستخدام الأدوات (Tool Calling) وتنفيذ سلاسل المهام المعقدة.',
    }),
    createSpecModule({
      id: 'ai_mod_18',
      num: '18',
      icon: '🌐',
      gradient: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
      titleAr: 'قيادة التحول الرقمي القائم على الذكاء الاصطناعي في المؤسسات',
      titleEn: 'Leading AI-Driven EdTech Transformation in Enterprises',
      titleFr: "Piloter la Transformation EdTech par l'IA en Entreprise",
      descAr: 'وضع استراتيجيات الاستثمار في الذكاء الاصطناعي، إدارة التغيير، وحوكمة الممارسات المؤسسية.',
      descEn: 'Formulating enterprise AI investment roadmaps, change management, and institutional governance.',
      descFr: "Stratégies d'investissement dans l'IA, conduite du changement et gouvernance.",
      trainerAr: 'نور الهدى صالحي',
      trainerEn: 'Nour El Houda Salhi',
      trainerFr: 'Nour El Houda Salhi',
      quizQuestionAr: 'ما هو التحدي الأكبر في التحول نحو الذكاء الاصطناعي بالمؤسسات؟',
      quizOptionsAr: [
        'شراء التراخيص فقط',
        'إدارة التغيير الثقافي وتأهيل الكوادر البشرية لاستيعاب واستثمار التقنية بفاعلية',
        'إلغاء الحواسيب الشخصية',
        'تقليص حجم المكاتب',
      ],
      quizAns: 1,
      quizExplanationAr: 'بناء الثقافة المؤسسية وتطوير المهارات البشرية هو العامل الحاسم لنجاح التحول التكنولوجي.',
    }),
  ];

  return {
    id: 'tech-ai',
    slug: 'tech-ai-trainer',
    specializationKey: 'tech',
    badge: 'AIT/101',
    title: {
      ar: 'مسار تدريب المدربين في الذكاء الاصطناعي التوليدي',
      en: 'Trainer Training Track in Generative Artificial Intelligence',
      fr: 'Parcours de formation des formateurs en Intelligence artificielle générative',
    },
    subtitle: {
      ar: 'رحلة تدريبية شاملة لاحتراف الذكاء الاصطناعي التوليدي وتطبيقاته في الأتمتة والإبداع والأعمال',
      en: 'A comprehensive training journey to master generative AI and its applications in automation, creativity, and business.',
      fr: "Un parcours complet pour maîtriser l'IA générative et ses applications.",
    },
    desc: {
      ar: 'مسار احترافي متقدم يؤهل المدربين المعاصرين لقيادة ثورة الذكاء الاصطناعي في بيئات التعلم. تتعلم خلاله هندسة الأوامر (Prompt Engineering) لإنتاج الحقائب التدريبية في دقائق، وتصميم شخصيات المحاكاة الذكية، وبناء وكلاء الأتمتة المتقدمين.',
      en: 'Advanced professional track empowering modern trainers to lead AI integration in education and training.',
      fr: 'Parcours avancé permettant aux formateurs d’intégrer l’IA générative.',
    },
    category: {
      ar: 'قسم تكنولوجيا التعليم / الذكاء الاصطناعي',
      en: 'EdTech / Artificial Intelligence',
      fr: 'EdTech / Intelligence Artificielle',
    },
    categoryBadgeText: { ar: 'تكنولوجيا', en: 'Technology', fr: 'Technologie' },
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=700&q=80',
    durationHours: 60,
    totalLessonsCount: 24,
    status: 'published',
    isAvailable: true,
    mode: { ar: 'عن بعد', en: 'Remote', fr: 'À distance' },
    modeKey: 'remote',
    mentor: {
      name: { ar: 'كريم زروقي', en: 'Karim Zerrougui', fr: 'Karim Zerrougui' },
      role: { ar: 'خبير حلول الذكاء الاصطناعي وتكنولوجيا التعليم', en: 'AI Solutions Architect', fr: 'Architecte IA' },
      img: 'https://i.pravatar.cc/60?img=22',
    },
    trainers: [
      { id: 'tr_kz', name: { ar: 'كريم زروقي', en: 'Karim Zerrougui', fr: 'Karim Zerrougui' }, role: { ar: 'كبير مهندسي الذكاء الاصطناعي', en: 'Lead AI Engineer', fr: 'Ingénieur IA Principal' }, img: 'https://i.pravatar.cc/60?img=22', isLead: true },
      { id: 'tr_ns', name: { ar: 'نور الهدى صالحي', en: 'Nour El Houda Salhi', fr: 'Nour El Houda Salhi' }, role: { ar: 'خبيرة التصميم التعليمي الذكي', en: 'Smart Instructional Design Expert', fr: 'Experte en Design Pédagogique' }, img: 'https://i.pravatar.cc/60?img=44' },
      { id: 'tr_ab', name: { ar: 'عادل بلحاج', en: 'Adel Belhadj', fr: 'Adel Belhadj' }, role: { ar: 'مستشار الأتمتة وتكامل الأنظمة', en: 'Automation & Integration Consultant', fr: 'Consultant en Automatisation' }, img: 'https://i.pravatar.cc/60?img=8' },
      { id: 'tr_it', name: { ar: 'إيمان تواتي', en: 'Imane Touati', fr: 'Imane Touati' }, role: { ar: 'أخصائية الوسائط التعليمية التوليدية', en: 'Generative Media Specialist', fr: 'Spécialiste Médias Génératifs' }, img: 'https://i.pravatar.cc/60?img=39' },
    ],
    levels: {
      foundation: {
        id: 'foundation',
        title: { ar: 'مستوى التأسيس في الذكاء الاصطناعي', en: 'AI Foundations Level', fr: 'Niveau Fondamental' },
        desc: { ar: 'المفاهيم، هندسة الأوامر، توليد النصوص والصور والأتمتة البسيطة', en: 'Core concepts, prompting, text/image generation and automation', fr: 'Concepts clés, prompting et génération' },
        badge: 'L1',
        modules: fndModules,
      },
      empowerment: {
        id: 'empowerment',
        title: { ar: 'مستوى التمكين والتطبيق المتقدم', en: 'AI Empowerment Level', fr: 'Niveau Habilitation' },
        desc: { ar: 'الأوامر المتقدمة، دمج الواجهات APIs، وتحليل البيانات التعليمية', en: 'Advanced prompting, API integrations, and predictive analytics', fr: 'Prompts avancés et intégrations API' },
        badge: 'L2',
        modules: empModules,
      },
      consolidation: {
        id: 'consolidation',
        title: { ar: 'مستوى التمتين والقيادة الاستراتيجية', en: 'AI Consolidation & Leadership', fr: 'Niveau Renforcement' },
        desc: { ar: 'بناء وكلاء الذكاء، قيادة التحول المؤسسي، والاستشارات المتقدمة', en: 'Autonomous AI agents, institutional transformation, and consulting', fr: 'Agents IA autonomes et gouvernance' },
        badge: 'L3',
        modules: conModules,
      },
    },
    finalExam: {
      title: { ar: 'الامتحان العام الشامل لمسار الذكاء الاصطناعي (AIT101)', en: 'Comprehensive AI Track Final Exam', fr: "Examen Final Complet de l'IA" },
      passingScore: 75,
      timeMinutes: 45,
      questions: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ------------------------------------------------------------------------------------------------
// 3. Track: Tech NoCode (NOC102)
// ------------------------------------------------------------------------------------------------
export function buildTechNoCodeTrack(): TrackDefinition {
  const fndModules: ModuleItem[] = [
    createSpecModule({
      id: 'noc_mod_01',
      num: '01',
      icon: '🧩',
      gradient: 'linear-gradient(135deg, #0284c7, #0369a1)',
      titleAr: 'مفهوم البرمجة بدون كود (No-Code Philosophy)',
      titleEn: 'No-Code Foundations & Paradigm Shift',
      titleFr: 'Fondamentaux du No-Code et Changement de Paradigme',
      descAr: 'فهم الثورة البرمجية الحديثة وكيفية بناء حلول رقمية احترافية بدون كتابة سطر كود واحد.',
      descEn: 'Understanding the no-code movement and building scalable systems without coding.',
      descFr: 'Comprendre le mouvement No-Code et créer des applications sans coder.',
      trainerAr: 'يوسف حمدي',
      trainerEn: 'Youcef Hamdi',
      trainerFr: 'Youcef Hamdi',
      quizQuestionAr: 'ما هي الفائدة الجوهرية لمنهجية التطوير بدون كود (No-Code)؟',
      quizOptionsAr: [
        'تقليل تكلفة ووقت إطلاق الحلول الرقمية بنسبة تصل إلى 80%',
        'منع المستخدم من تعديل البيانات',
        'إلغاء الاتصال بقواعد البيانات',
        'العمل على الأجهزة القديمة فقط',
      ],
      quizAns: 0,
      quizExplanationAr: 'الـ No-Code يختصر زمن طرح المنتج في السوق (Time to Market) ويوفر تكاليف البرمجة التقليدية الباهظة.',
    }),
    createSpecModule({
      id: 'noc_mod_02',
      num: '02',
      icon: '🗄️',
      gradient: 'linear-gradient(135deg, #0d9488, #14b8a6)',
      titleAr: 'هيكلة وتصميم قواعد البيانات السحابية (Cloud Databases)',
      titleEn: 'Cloud Database Architecture for No-Code Systems',
      titleFr: 'Architecture des Bases de Données Cloud No-Code',
      descAr: 'تصميم الجداول، العلاقات (1-to-many, many-to-many)، والحقول الديناميكية.',
      descEn: 'Relational data modeling, table structures, and dynamic relationships in Airtable & Supabase.',
      descFr: 'Modélisation relationnelle et gestion des données dans Airtable et Supabase.',
      trainerAr: 'كريم زروقي',
      trainerEn: 'Karim Zerrougui',
      trainerFr: 'Karim Zerrougui',
      quizQuestionAr: 'ما أهمية تحديد العلاقات الصحيحة بين الجداول في قواعد البيانات؟',
      quizOptionsAr: [
        'لزيادة استهلاك الذاكرة',
        'لمنع تكرار البيانات وضمان سلامة وتناسق المعلومات عبر كافة شاشات التطبيق',
        'لتغيير ألوان الواجهة',
        'لإلغاء صلاحيات المستخدمين',
      ],
      quizAns: 1,
      quizExplanationAr: 'التطبيع والعلاقات السليمة تمنع التناقض وتضمن سرعة استرجاع البيانات بدقة عالية.',
    }),
    createSpecModule({
      id: 'noc_mod_03',
      num: '03',
      icon: '🖥️',
      gradient: 'linear-gradient(135deg, #4f46e5, #6366f1)',
      titleAr: 'تصميم واجهات المستخدم الحديثة (UI/UX for No-Code)',
      titleEn: 'Modern UI/UX Design for No-Code Web Apps',
      titleFr: 'Design UI/UX Moderne pour Applications No-Code',
      descAr: 'بناء واجهات متجاوبة على الموبايل والتابلت والكمبيوتر مع مراعاة راحة العين وتجربة التعلم.',
      descEn: 'Responsive layout engineering, accessible typography, and intuitive user journeys.',
      descFr: 'Mise en page réactive et parcours utilisateur intuitifs pour le web.',
      trainerAr: 'نور الهدى صالحي',
      trainerEn: 'Nour El Houda Salhi',
      trainerFr: 'Nour El Houda Salhi',
      quizQuestionAr: 'ما هو المبدأ الأساسي في التصميم المتجاوب (Responsive Design)؟',
      quizOptionsAr: [
        'تثبيت أبعاد الشاشة برقم بكسل ثابت لجميع الأجهزة',
        'تكيف العناصر والخطوط والقوائم تلقائياً مع حجم ودقة كل شاشة لراحة المستخدم',
        'إلغاء دعم الهواتف الذكية',
        'تصغير الخطوط حتى تصبح غير مقروءة',
      ],
      quizAns: 1,
      quizExplanationAr: 'التصميم المتجاوب يضمن تجربة سلسة سواء دخل المتدرب من هاتف، تابلت أو حاسوب مكتبي.',
    }),
    createSpecModule({
      id: 'noc_mod_04',
      num: '04',
      icon: '🌐',
      gradient: 'linear-gradient(135deg, #2563eb, #3b82f6)',
      titleAr: 'تطوير صفحات الهبوط وبوابات التسجيل الذكية',
      titleEn: 'High-Converting Landing Pages & Registration Portals',
      titleFr: "Pages d'Atterrissage et Portails d'Inscription",
      descAr: 'بناء صفحات تسويقية سريعة، نماذج جمع المتدربين، وربط التحليلات المتقدمة.',
      descEn: 'Rapid landing page development, lead capture forms, and analytics integration.',
      descFr: "Création rapide de pages d'atterrissage et formulaires de conversion.",
      trainerAr: 'أحمد بن الشيخ',
      trainerEn: 'Ahmed Bencheikh',
      trainerFr: 'Ahmed Bencheikh',
      quizQuestionAr: 'ما العنصر الأهم لرفع نسبة التحويل (Conversion Rate) في صفحة الهبوط؟',
      quizOptionsAr: [
        'كثرة النصوص الطويلة وغير المنسقة',
        'وضوح العرض القيّم (Value Proposition) وزر دعوة لاتخاذ إجراء مباشر (CTA) وبارز',
        'إخفاء معلومات التواصل',
        'تعقيد استمارة التسجيل بـ 50 حقلاً إجبارياً',
      ],
      quizAns: 1,
      quizExplanationAr: 'الوضوح والسهولة مع زر إجراء رئيسي جذاب وموجز يضاعف معدل تسجيل المتدربين.',
    }),
  ];

  return {
    id: 'tech-nocode',
    slug: 'tech-nocode',
    specializationKey: 'tech',
    badge: 'NOC/102',
    title: {
      ar: 'مسار تدريب المدربين في البرمجة بدون كود',
      en: 'Trainer Training Track in No-Code Development',
      fr: 'Parcours de formation des formateurs en Développement sans code (No-Code)',
    },
    subtitle: {
      ar: 'تعلم بناء تطبيقات وأنظمة متكاملة دون كتابة كود عبر أدوات اللاكود الحديثة',
      en: 'Learn to build integrated apps and systems without writing code, using modern no-code tools.',
      fr: 'Apprenez à créer des applications complètes sans écrire de code.',
    },
    desc: {
      ar: 'مسار تأهيلي عملي يمكن المدربين والمؤسسات من بناء منصاتهم التعليمية، بوابات التسجيل، أنظمة إدارة المتدربين، وأتمتة الفواتير والشهادات بالكامل دون الحاجة لمبرمجين أو استنزاف الميزانيات البرمجية.',
      en: 'Hands-on qualification track enabling educators to build end-to-end LMS portals, registration funnels, and automated operations.',
      fr: 'Parcours pratique pour concevoir des plateformes LMS et des flux de travail sans développeurs.',
    },
    category: {
      ar: 'قسم تكنولوجيا التعليم / البرمجة بدون كود',
      en: 'EdTech / No-Code Development',
      fr: 'EdTech / Développement No-Code',
    },
    categoryBadgeText: { ar: 'تكنولوجيا', en: 'Technology', fr: 'Technologie' },
    coverImage: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=700&q=80',
    durationHours: 65,
    totalLessonsCount: 24,
    status: 'published',
    isAvailable: true,
    mode: { ar: 'عن بعد', en: 'Remote', fr: 'À distance' },
    modeKey: 'remote',
    mentor: {
      name: { ar: 'يوسف حمدي', en: 'Youcef Hamdi', fr: 'Youcef Hamdi' },
      role: { ar: 'خبير الأنظمة السحابية وحلول الـ No-Code', en: 'Cloud & No-Code Architect', fr: 'Architecte Cloud No-Code' },
      img: 'https://i.pravatar.cc/60?img=15',
    },
    trainers: [
      { id: 'tr_yh', name: { ar: 'يوسف حمدي', en: 'Youcef Hamdi', fr: 'Youcef Hamdi' }, role: { ar: 'كبير مهندسي الـ No-Code', en: 'Lead No-Code Engineer', fr: 'Ingénieur No-Code' }, img: 'https://i.pravatar.cc/60?img=15', isLead: true },
      { id: 'tr_kz', name: { ar: 'كريم زروقي', en: 'Karim Zerrougui', fr: 'Karim Zerrougui' }, role: { ar: 'خبير قواعد البيانات والأتمتة', en: 'Database & Automation Lead', fr: 'Expert Bases de Données' }, img: 'https://i.pravatar.cc/60?img=22' },
      { id: 'tr_ns', name: { ar: 'نور الهدى صالحي', en: 'Nour El Houda Salhi', fr: 'Nour El Houda Salhi' }, role: { ar: 'مصممة واجهات وتجربة المستخدم', en: 'Product & UI Designer', fr: 'Designer UI/UX' }, img: 'https://i.pravatar.cc/60?img=44' },
      { id: 'tr_ab', name: { ar: 'أحمد بن الشيخ', en: 'Ahmed Bencheikh', fr: 'Ahmed Bencheikh' }, role: { ar: 'أخصائي بوابات الدفع والربط الرقمي', en: 'Integrations & Payments Specialist', fr: 'Spécialiste Paiements' }, img: 'https://i.pravatar.cc/60?img=12' },
    ],
    levels: {
      foundation: {
        id: 'foundation',
        title: { ar: 'مستوى تأسيس أنظمة اللاكود', en: 'No-Code Foundations', fr: 'Bases du No-Code' },
        desc: { ar: 'مفاهيم اللاكود، قواعد البيانات السحابية، تصميم الواجهات وصفحات الهبوط', en: 'Core paradigm, cloud databases, UI design and landing pages', fr: 'Bases relationnelles, interfaces et pages web' },
        badge: 'L1',
        modules: fndModules,
      },
    },
    finalExam: {
      title: { ar: 'الامتحان النهائي لمسار البرمجة بدون كود (NOC102)', en: 'No-Code Track Final Exam', fr: 'Examen Final No-Code' },
      passingScore: 70,
      timeMinutes: 40,
      questions: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ------------------------------------------------------------------------------------------------
// 4. Track: Tech Data & BI (DBI103)
// ------------------------------------------------------------------------------------------------
export function buildTechDataBiTrack(): TrackDefinition {
  const fndModules: ModuleItem[] = [
    createSpecModule({
      id: 'dbi_mod_01',
      num: '01',
      icon: '📈',
      gradient: 'linear-gradient(135deg, #059669, #10b981)',
      titleAr: 'مفاهيم البيانات وذكاء الأعمال للمدربين',
      titleEn: 'Data Concepts & Business Intelligence Essentials',
      titleFr: "Concepts des Données et Business Intelligence",
      descAr: 'كيف تقرأ مؤشرات الأداء، وتفهم احتياجات المتدربين من خلال الأرقام، وتتخذ قرارات قائمة على الدليل.',
      descEn: 'Interpreting training KPIs and making evidence-based curriculum decisions.',
      descFr: 'Interpréter les indicateurs clés et prendre des décisions basées sur les données.',
      trainerAr: 'لينة بوزيان',
      trainerEn: 'Lina Bouziane',
      trainerFr: 'Lina Bouziane',
      quizQuestionAr: 'ما هو الفرق الرئيسي بين "البيانات الخام" و"ذكاء الأعمال (BI)"؟',
      quizOptionsAr: [
        'لا يوجد فرق بينهما',
        'البيانات أرقام مجردة، بينما ذكاء الأعمال يحولها إلى رؤى استراتيجية قابلة للتنفيذ الفوري',
        'ذكاء الأعمال متاح فقط للشركات الكبرى ولا يفيد التدريب',
        'البيانات الخام دائماً خاطئة',
      ],
      quizAns: 1,
      quizExplanationAr: 'ذكاء الأعمال يستخرج الأنماط ويوجه اتخاذ القرارات التطويرية بدقة وموضوعية.',
    }),
    createSpecModule({
      id: 'dbi_mod_02',
      num: '02',
      icon: '📊',
      gradient: 'linear-gradient(135deg, #0284c7, #06b6d4)',
      titleAr: 'جمع وتنظيف وتجهيز البيانات التدريبية (Data Cleaning)',
      titleEn: 'Data Cleaning & Preprocessing for Educators',
      titleFr: 'Collecte, Nettoyage et Préparation des Données',
      descAr: 'معالجة القيم المفقودة، توحيد صيغ التقييمات، وتنقية بيانات استطلاعات الرأي.',
      descEn: 'Handling missing values, standardizing scores, and processing feedback survey datasets.',
      descFr: 'Traitement des valeurs manquantes et harmonisation des évaluations.',
      trainerAr: 'نور الهدى صالحي',
      trainerEn: 'Nour El Houda Salhi',
      trainerFr: 'Nour El Houda Salhi',
      quizQuestionAr: 'لماذا تعتبر مرحلة تنظيف البيانات (Data Cleaning) حاسمة؟',
      quizOptionsAr: [
        'لأن التحليلات الخاطئة الناتجة عن بيانات غير دقيقة تؤدي لقرارات تدريبية مضللة',
        'لأنها تزيد حجم الملفات',
        'لإلغاء البيانات السلبية عن الدورة',
        'لأنها خطوة اختيارية لا تأثير لها',
      ],
      quizAns: 0,
      quizExplanationAr: 'مبدأ Garbage In, Garbage Out يؤكد أن جودة القرار تعتمد كلياً على نقاء البيانات.',
    }),
    createSpecModule({
      id: 'dbi_mod_03',
      num: '03',
      icon: '📉',
      gradient: 'linear-gradient(135deg, #d97706, #f59e0b)',
      titleAr: 'الإحصاء الوصفي ومؤشرات قياس الأداء (KPIs)',
      titleEn: 'Descriptive Statistics & Learning KPIs',
      titleFr: 'Statistiques Descriptives et Indicateurs Clés',
      descAr: 'حساب المتوسطات، الانحراف المعياري، معدلات النجاح، ونسب الاحتفاظ بالمتدربين.',
      descEn: 'Calculating means, variance, completion rates, and cohort retention metrics.',
      descFr: 'Calcul des moyennes, taux de complétion et rétention des apprenants.',
      trainerAr: 'إيمان تواتي',
      trainerEn: 'Imane Touati',
      trainerFr: 'Imane Touati',
      quizQuestionAr: 'ما هو مؤشر اكتمال المسار (Course Completion Rate)؟',
      quizOptionsAr: [
        'عدد الذين زاروا صفحة الدورة',
        'نسبة المتدربين الذين أتموا كافة متطلبات المسار بنجاح من إجمالي المسجلين',
        'عدد المحاضرين في الدورة',
        'سعر البرنامج التدريبي',
      ],
      quizAns: 1,
      quizExplanationAr: 'معدل الإكمال يقيس فاعلية وجاذبية المحتوى وقدرته على إبقاء المتدرب متحمساً للنهاية.',
    }),
    createSpecModule({
      id: 'dbi_mod_04',
      num: '04',
      icon: '🖥️',
      gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
      titleAr: 'بناء لوحات القيادة التفاعلية (Interactive Dashboards)',
      titleEn: 'Interactive Dashboard Building (Power BI / Looker Studio)',
      titleFr: 'Création de Tableaux de Bord Interactifs',
      descAr: 'تصميم شاشات متابعة حية تعرض تطور المتدربين ومؤشرات العائد بضغطة زر.',
      descEn: 'Synthesizing live progress dashboards, revenue trackers, and trainee performance visuals.',
      descFr: 'Conception de dashboards en temps réel pour le suivi de la performance.',
      trainerAr: 'سارة مرابط',
      trainerEn: 'Sara Merabet',
      trainerFr: 'Sara Merabet',
      quizQuestionAr: 'ما هي الخاصية الأهم في لوحة القيادة (Dashboard) الناجحة؟',
      quizOptionsAr: [
        'ازدحام الألوان والرسوم العشوائية المعقدة',
        'البساطة، وضوح المؤشرات، وسهولة تصفية واستخلاص المعنى في ثوانٍ معدودة',
        'عرض الأرقام القديمة فقط',
        'منع المستخدم من النقر والتفاعل',
      ],
      quizAns: 1,
      quizExplanationAr: 'لوحة القيادة الممتازة تجيب عن الأسئلة الحيوية للمدرب في لمحة بصرية سريعة ومنظمة.',
    }),
  ];

  return {
    id: 'tech-data-bi',
    slug: 'tech-data-bi',
    specializationKey: 'tech',
    badge: 'DBI/103',
    title: {
      ar: 'مسار تدريب المدربين في تحليل البيانات وذكاء الأعمال',
      en: 'Trainer Training Track in Data Analysis & Business Intelligence',
      fr: "Parcours de formation des formateurs en Analyse de données et intelligence d'affaires",
    },
    subtitle: {
      ar: 'امتلك مهارات تحليل البيانات واتخاذ القرار الذكي عبر أدوات ولوحات القيادة',
      en: 'Master data analysis skills and smart decision-making using tools and dashboards.',
      fr: 'Maîtrisez les compétences d’analyse de données et de prise de décision.',
    },
    desc: {
      ar: 'مسار نوعي مخصص للمدربين ومسؤولي التطوير المؤسسي (L&D) لتمكينهم من قياس أثر التدريب، وبناء لوحات المتابعة التفاعلية، وتحويل استبيانات التقييم إلى خطط تطوير ملموسة وذات عائد مثبت.',
      en: 'Specialized track for trainers and L&D leaders to measure ROI, build performance dashboards, and translate survey metrics into actionable development roadmaps.',
      fr: 'Parcours pour mesurer le ROI de la formation et concevoir des tableaux de bord interactifs.',
    },
    category: {
      ar: 'قسم تكنولوجيا التعليم / تحليل البيانات',
      en: 'EdTech / Data Analysis & BI',
      fr: 'EdTech / Analyse de Données',
    },
    categoryBadgeText: { ar: 'تكنولوجيا', en: 'Technology', fr: 'Technologie' },
    coverImage: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=700&q=80',
    durationHours: 62,
    totalLessonsCount: 24,
    status: 'published',
    isAvailable: true,
    mode: { ar: 'حضوري', en: 'In-person', fr: 'Présentiel' },
    modeKey: 'onsite',
    mentor: {
      name: { ar: 'لينة بوزيان', en: 'Lina Bouziane', fr: 'Lina Bouziane' },
      role: { ar: 'خبيرة ذكاء الأعمال وتحليل البيانات المؤسسية', en: 'BI & Analytics Director', fr: 'Directrice BI' },
      img: 'https://i.pravatar.cc/60?img=32',
    },
    trainers: [
      { id: 'tr_lb', name: { ar: 'لينة بوزيان', en: 'Lina Bouziane', fr: 'Lina Bouziane' }, role: { ar: 'رئيسة قسم ذكاء الأعمال', en: 'Head of Business Intelligence', fr: 'Responsable BI' }, img: 'https://i.pravatar.cc/60?img=32', isLead: true },
      { id: 'tr_ns', name: { ar: 'نور الهدى صالحي', en: 'Nour El Houda Salhi', fr: 'Nour El Houda Salhi' }, role: { ar: 'أخصائية إحصاء ونمذجة بيانات', en: 'Data Modeling Specialist', fr: 'Spécialiste Modélisation' }, img: 'https://i.pravatar.cc/60?img=44' },
      { id: 'tr_it', name: { ar: 'إيمان تواتي', en: 'Imane Touati', fr: 'Imane Touati' }, role: { ar: 'مستشارة تحليلات الأداء التعليمي', en: 'Learning Analytics Consultant', fr: 'Consultante Analytics' }, img: 'https://i.pravatar.cc/60?img=39' },
      { id: 'tr_sm', name: { ar: 'سارة مرابط', en: 'Sara Merabet', fr: 'Sara Merabet' }, role: { ar: 'مهندسة لوحات القيادة التفاعلية', en: 'Dashboard Visualization Engineer', fr: 'Ingénieure Visualisation' }, img: 'https://i.pravatar.cc/60?img=47' },
    ],
    levels: {
      foundation: {
        id: 'foundation',
        title: { ar: 'مستوى تأسيس تحليل البيانات', en: 'Data Foundations', fr: 'Bases de la Donnée' },
        desc: { ar: 'مفاهيم البيانات، التنظيف، الإحصاء الوصفي ولوحات القيادة', en: 'Data fundamentals, cleaning, descriptive statistics, and dashboards', fr: 'Nettoyage des données, statistiques et tableaux de bord' },
        badge: 'L1',
        modules: fndModules,
      },
    },
    finalExam: {
      title: { ar: 'الامتحان العام الشامل في تحليل البيانات وذكاء الأعمال (DBI103)', en: 'Data & BI Track Final Exam', fr: 'Examen Final Data & BI' },
      passingScore: 70,
      timeMinutes: 45,
      questions: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ------------------------------------------------------------------------------------------------
// 5. Track: Marketing (MKT202)
// ------------------------------------------------------------------------------------------------
export function buildMarketingTrack(): TrackDefinition {
  const fndModules: ModuleItem[] = [
    createSpecModule({
      id: 'mkt_mod_01',
      num: '01',
      icon: '🎯',
      gradient: 'linear-gradient(135deg, #d97706, #ef4444)',
      titleAr: 'هندسة العرض القيّم وبناء مسارات البيع (Value Funnels)',
      titleEn: 'Value Proposition Engineering & Sales Funnels',
      titleFr: 'Proposition de Valeur et Tunnels de Vente',
      descAr: 'كيف تصيغ الوعد التحويلي وتجذب المتدربين والشركات بوضوح وجاذبية.',
      descEn: 'Formulating transformational promises and attracting enterprise clients.',
      descFr: 'Formuler la promesse de transformation et attirer les entreprises.',
      trainerAr: 'سارة مرابط',
      trainerEn: 'Sara Merabet',
      trainerFr: 'Sara Merabet',
      quizQuestionAr: 'ما الفرق بين بيع "ساعات التدريب" وبيع "الوعد التحويلي"؟',
      quizOptionsAr: [
        'لا يوجد أي فرق حقيقي',
        'الوعد التحويلي يركز على المهارة والنتيجة الملموسة التي يكتسبها المتدرب، وهو ما تدفع الشركات لأجله',
        'ساعات التدريب دائماً أعلى قيمة',
        'الوعد التحويلي للمؤسسات الخيرية فقط',
      ],
      quizAns: 1,
      quizExplanationAr: 'المتدربون والمؤسسات يستثمرون في النتائج والحلول العملية وليس في عدد الساعات المجردة.',
    }),
    createSpecModule({
      id: 'mkt_mod_02',
      num: '02',
      icon: '📢',
      gradient: 'linear-gradient(135deg, #f59e0b, #ea580c)',
      titleAr: 'التسويق عبر المحتوى وبناء السلطة المعرفية (Content Marketing)',
      titleEn: 'Authority-Driven Content Marketing & Thought Leadership',
      titleFr: 'Marketing de Contenu et Leadership d’Opinion',
      descAr: 'كتابة مقالات تخصصية، منشورات لينكد إن، وبناء الثقة الرقمية كمرجع أول في مجالك.',
      descEn: 'Writing technical case posts, LinkedIn thought leadership, and building organic trust.',
      descFr: 'Rédaction d’articles spécialisés et acquisition de crédibilité sur LinkedIn.',
      trainerAr: 'لينة بوزيان',
      trainerEn: 'Lina Bouziane',
      trainerFr: 'Lina Bouziane',
      quizQuestionAr: 'ما هو الهدف الأسمى للتسويق بالمحتوى للمدرب المحترف؟',
      quizOptionsAr: [
        'جمع الإعجابات العشوائية فقط',
        'بناء المصداقية وترسيخ مكانته كخبير موثوق يستقطب العملاء عضوياً (Inbound Marketing)',
        'إغراق المتابعين بإعلانات بيع متكررة ومزعجة',
        'الحديث في كل المواضيع غير ذات الصلة',
      ],
      quizAns: 1,
      quizExplanationAr: 'المحتوى القيّم يبني علاقة ثقة تجعل العميل يبحث عنك بنفسه لطلب استشاراتك وبرامجك.',
    }),
    createSpecModule({
      id: 'mkt_mod_03',
      num: '03',
      icon: '📱',
      gradient: 'linear-gradient(135deg, #b45309, #d97706)',
      titleAr: 'إعلانات السوشيال ميديا والحملات الممولة (Paid Advertising)',
      titleEn: 'Paid Acquisition & Social Media Ad Campaigns',
      titleFr: 'Campagnes Publicitaires et Acquisition Payante',
      descAr: 'استهداف الشريحة المستفيدة عبر فيسبوك، إنستغرام، وجوجل وحساب العائد (ROAS).',
      descEn: 'Targeting high-intent audiences on Meta & Google Ads and maximizing ROAS.',
      descFr: 'Ciblage d’audiences qualifiées et optimisation du retour sur investissement publicitaire.',
      trainerAr: 'نور الهدى صالحي',
      trainerEn: 'Nour El Houda Salhi',
      trainerFr: 'Nour El Houda Salhi',
      quizQuestionAr: 'ما هو مؤشر ROAS في الحملات الإعلانية؟',
      quizOptionsAr: [
        'عدد المتابعين الجدد فقط',
        'العائد على الإنفاق الإعلاني (Return on Ad Spend) لمعرفة كل دينار أنفق كم حقق من إيرادات',
        'سرعة تحميل الفيديو الإعلاني',
        'نوع الخط المستخدم في الإعلان',
      ],
      quizAns: 1,
      quizExplanationAr: 'مؤشر ROAS يقيس الربحية الدقيقة للحملة ويضمن عدم هدر الميزانيات التسويقية.',
    }),
    createSpecModule({
      id: 'mkt_mod_04',
      num: '04',
      icon: '💌',
      gradient: 'linear-gradient(135deg, #c2410c, #f97316)',
      titleAr: 'التسويق بالبريد الإلكتروني وأتمتة رعاية العملاء (Email Nurturing)',
      titleEn: 'Email Marketing & Automated Trainee Nurturing',
      titleFr: 'Email Marketing et Fidélisation Automatisée',
      descAr: 'إعداد سلاسل الرسائل الترحيبية، النشرات البريدية المتخصصة، وتحويل المهتمين إلى مشتركين دائمين.',
      descEn: 'Architecting welcome sequences, educational newsletters, and automated conversions.',
      descFr: 'Séquences de bienvenue, newsletters éducatives et conversion automatique.',
      trainerAr: 'إيمان تواتي',
      trainerEn: 'Imane Touati',
      trainerFr: 'Imane Touati',
      quizQuestionAr: 'لماذا يُعتبر البريد الإلكتروني القناة التسويقية الأعلى عائداً تاريخياً؟',
      quizOptionsAr: [
        'لأنه مجاني دائماً بدون أي اشتراك',
        'لأنه قناة تواصل مباشرة تمتلكها بالكامل دون تحكم خوارزميات منصات التواصل المتقلبة',
        'لأنه لا يحتاج لكتابة أي نصوص',
        'لأنه لا يقرأه أحد',
      ],
      quizAns: 1,
      quizExplanationAr: 'القائمة البريدية أصل رقمي خاص للمدرب يضمن وصول رسائله مباشرة إلى صندوق وارد العميل.',
    }),
  ];

  return {
    id: 'marketing-digital',
    slug: 'marketing-growth',
    specializationKey: 'marketing',
    badge: 'MKT/202',
    title: {
      ar: 'مسار تدريب المدربين في التسويق الإلكتروني',
      en: 'Trainer Training Track in Digital Marketing',
      fr: 'Parcours de formation des formateurs en Marketing électronique',
    },
    subtitle: {
      ar: 'دليلك العملي لبناء استراتيجيات تسويق رقمي فعّالة وقياس الأداء وتحقيق النمو',
      en: 'Your practical guide to building effective digital marketing strategies, measuring performance, and achieving growth.',
      fr: 'Votre guide pratique pour élaborer des stratégies de marketing numérique efficaces.',
    },
    desc: {
      ar: 'مسار احترافي متقدم يسلح المدربين ورواد الأعمال المعرفية بأقوى استراتيجيات التسويق الرقمي، قمع المبيعات، بناء العلامة الشخصية الموثوقة، وإطلاق البرامج التدريبية بنجاح واستدامة ربحية.',
      en: 'Equipping professional trainers with client acquisition funnels, digital branding, and revenue-generating marketing systems.',
      fr: 'Fournir aux formateurs des stratégies avancées pour créer leur marque et attirer des apprenants.',
    },
    category: {
      ar: 'قسم التسويق الرقمي / العلامة الشخصية',
      en: 'Digital Marketing / Personal Branding',
      fr: 'Marketing Digital / Branding',
    },
    categoryBadgeText: { ar: 'تسويق', en: 'Marketing', fr: 'Marketing' },
    coverImage: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=700&q=80',
    durationHours: 50,
    totalLessonsCount: 24,
    status: 'published',
    isAvailable: true,
    mode: { ar: 'عن بعد', en: 'Remote', fr: 'À distance' },
    modeKey: 'remote',
    mentor: {
      name: { ar: 'سارة مرابط', en: 'Sara Merabet', fr: 'Sara Merabet' },
      role: { ar: 'استشارية التسويق الرقمي وبناء العلامات المعرفية', en: 'Digital Marketing Director', fr: 'Directrice Marketing' },
      img: 'https://i.pravatar.cc/60?img=47',
    },
    trainers: [
      { id: 'tr_sm', name: { ar: 'سارة مرابط', en: 'Sara Merabet', fr: 'Sara Merabet' }, role: { ar: 'كبيرة استشاريي التسويق الرقمي', en: 'Lead Marketing Strategist', fr: 'Stratège Marketing' }, img: 'https://i.pravatar.cc/60?img=47', isLead: true },
      { id: 'tr_lb', name: { ar: 'لينة بوزيان', en: 'Lina Bouziane', fr: 'Lina Bouziane' }, role: { ar: 'خبيرة التسويق بالمحتوى والنمو العضوي', en: 'Content Marketing Expert', fr: 'Experte Marketing Contenu' }, img: 'https://i.pravatar.cc/60?img=32' },
      { id: 'tr_ns', name: { ar: 'نور الهدى صالحي', en: 'Nour El Houda Salhi', fr: 'Nour El Houda Salhi' }, role: { ar: 'أخصائية الإعلانات الممولة ومسارات البيع', en: 'Paid Acquisition Specialist', fr: 'Spécialiste Publicités' }, img: 'https://i.pravatar.cc/60?img=44' },
      { id: 'tr_it', name: { ar: 'إيمان تواتي', en: 'Imane Touati', fr: 'Imane Touati' }, role: { ar: 'خبيرة الأتمتة والتسويق بالبريد', en: 'Email & CRM Specialist', fr: 'Spécialiste CRM' }, img: 'https://i.pravatar.cc/60?img=39' },
    ],
    levels: {
      foundation: {
        id: 'foundation',
        title: { ar: 'مستوى تأسيس التسويق الرقمي', en: 'Marketing Foundations', fr: 'Bases du Marketing' },
        desc: { ar: 'هندسة العرض القيّم، صناعة المحتوى، الإعلانات الممولة، وأتمتة البريد', en: 'Value propositions, content marketing, paid ads, and email nurturing', fr: 'Proposition de valeur, publicité et CRM' },
        badge: 'L1',
        modules: fndModules,
      },
    },
    finalExam: {
      title: { ar: 'الامتحان العام الشامل في التسويق الرقمي (MKT202)', en: 'Digital Marketing Track Final Exam', fr: 'Examen Final Marketing' },
      passingScore: 70,
      timeMinutes: 45,
      questions: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ------------------------------------------------------------------------------------------------
// 6. Track: Media & Journalism (MED301)
// ------------------------------------------------------------------------------------------------
export function buildMediaJournalismTrack(): TrackDefinition {
  const fndModules: ModuleItem[] = [
    createSpecModule({
      id: 'med_mod_01',
      num: '01',
      icon: '🎙️',
      gradient: 'linear-gradient(135deg, #e11d48, #be123c)',
      titleAr: 'مدخل للإعلام الرقمي وأخلاقيات النشر',
      titleEn: 'Digital Media Foundations & Publishing Ethics',
      titleFr: 'Fondamentaux des Médias et Éthique de Publication',
      descAr: 'قوانين الإعلام، التحقق من المصادر، ومسؤولية المدرب والمراسل في الفضاء الرقمي.',
      descEn: 'Media legislation, source verification, and digital communication integrity.',
      descFr: 'Législation des médias, vérification des sources et déontologie.',
      trainerAr: 'أحمد بن الشيخ',
      trainerEn: 'Ahmed Bencheikh',
      trainerFr: 'Ahmed Bencheikh',
      quizQuestionAr: 'ما هو المبدأ المهني الأول عند نقل أي خبر أو معلومة رقمية؟',
      quizOptionsAr: [
        'النشر الفوري والتسرع قبل أي تحقق لجذب المشاهدات',
        'التحقق الدقيق من المصادر الأصلية والمصداقية ومراعاة حقوق النشر والخصوصية',
        'نقل الشائعات إذا كانت مشوقة',
        'حذف أسماء المصادر الحقيقية',
      ],
      quizAns: 1,
      quizExplanationAr: 'المصداقية هي الرأسمال الأول للإعلامي والمؤسسة ولا مجال للمغامرة بنشر أخبار غير مؤكدة.',
    }),
    createSpecModule({
      id: 'med_mod_02',
      num: '02',
      icon: '✍️',
      gradient: 'linear-gradient(135deg, #c026d3, #a21caf)',
      titleAr: 'التحرير الصحفي وصياغة العناوين الجذابة (Digital Copywriting)',
      titleEn: 'Digital Journalism Copywriting & Engaging Headlines',
      titleFr: 'Rédaction Journalistique et Titrage Numérique',
      descAr: 'هيكلة المقال الصحفي الحديث، تقنية الهرم المقلوب، والكتابة الرقمية السلسة.',
      descEn: 'Inverted pyramid writing, punchy lead sentences, and web-friendly editorial style.',
      descFr: 'Technique de la pyramide inversée et écriture web percutante.',
      trainerAr: 'سارة مرابط',
      trainerEn: 'Sara Merabet',
      trainerFr: 'Sara Merabet',
      quizQuestionAr: 'ما هي تقنية "الهرم المقلوب" (Inverted Pyramid) في التحرير الصحفي؟',
      quizOptionsAr: [
        'وضع أهم معلومة في نهاية المقال',
        'بدء المقال بأهم وأبرز المعلومات في المقدمة، تليها التفاصيل الداعمة ثم الخلفيات العامة',
        'كتابة المقال دون أي مقدمة',
        'استخدام كلمات صعبة ومعقدة في البداية',
      ],
      quizAns: 1,
      quizExplanationAr: 'الهرم المقلوب يتيح للقارئ الرقمي معرفة جوهر الخبر في الثواني الخمس الأولى.',
    }),
    createSpecModule({
      id: 'med_mod_03',
      num: '03',
      icon: '📷',
      gradient: 'linear-gradient(135deg, #ea580c, #c2410c)',
      titleAr: 'التصوير الصحفي وصحافة الموبايل (Mobile Journalism - MoJo)',
      titleEn: 'Photojournalism & Mobile Journalism (MoJo)',
      titleFr: 'Photojournalisme et Journalisme Mobile (MoJo)',
      descAr: 'قواعد التكوين البصري، الإضاءة الميدانية، وتصوير التقارير الاحترافية بالهاتف الذكي.',
      descEn: 'Framing, lighting, audio capture, and field reporting using smartphones.',
      descFr: 'Cadrage, éclairage et reportages professionnels au smartphone.',
      trainerAr: 'يوسف حمدي',
      trainerEn: 'Youcef Hamdi',
      trainerFr: 'Youcef Hamdi',
      quizQuestionAr: 'ما هو العنصر التقني الذي يتسبب في إفساد فيديو تقرير الموبايل أكثر من غيره؟',
      quizOptionsAr: [
        'جودة الصوت الرديئة والضوضاء المحيطة',
        'حجم الهاتف',
        'لون خلفية الجدار',
        'طول المقابلة',
      ],
      quizAns: 0,
      quizExplanationAr: 'المشاهد قد يتسامح مع صورة متوسطة لكنه يغادر فوراً إذا كان الصوت رديئاً أو مشوشاً.',
    }),
    createSpecModule({
      id: 'med_mod_04',
      num: '04',
      icon: '🎙️',
      gradient: 'linear-gradient(135deg, #7c3aed, #6d28d9)',
      titleAr: 'فنون البودكاست وإدارة المقابلات الإعلامية الحوارية',
      titleEn: 'Podcasting & Media Interviewing Techniques',
      titleFr: 'Production de Podcast et Techniques d’Interview',
      descAr: 'هندسة الحلقة الحوارية، إعداد الأسئلة الاستقصائية، والتحكم في نبرة الصوت والإيقاع.',
      descEn: 'Podcast structuring, insightful question formulation, and vocal modulation.',
      descFr: 'Structuration de podcasts et conduite d’interviews percutantes.',
      trainerAr: 'لينة بوزيان',
      trainerEn: 'Lina Bouziane',
      trainerFr: 'Lina Bouziane',
      quizQuestionAr: 'ما هي الطريقة الفعالة لإجراء مقابلة حوارية ثرية وممتعة؟',
      quizOptionsAr: [
        'تلاوة قائمة الأسئلة بشكل آلي دون الاستماع لإجابات الضيف',
        'الاستماع النشط، والبناء على كلام الضيف بأسئلة متابعة ذكية وغير متوقعة',
        'مقاطعة الضيف باستمرار',
        'الإجابة عن الأسئلة بدلاً من الضيف',
      ],
      quizAns: 1,
      quizExplanationAr: 'الاستماع النشط هو سر كل مقابلة إعلامية استثنائية تكشف حقائق جديدة للمشاهد.',
    }),
  ];

  return {
    id: 'media-journalism',
    slug: 'media-journalism',
    specializationKey: 'media',
    badge: 'MED/301',
    title: {
      ar: 'مسار تدريب المدربين في الإعلام الرقمي وصحافة الويب',
      en: 'Trainer Training Track in Digital Media & Web Journalism',
      fr: 'Parcours de formation des formateurs en Médias numériques et journalisme web',
    },
    subtitle: {
      ar: 'مسار متكامل لتكوين صحفيين ومدربي محتوى رقمي محترفين، من الأساسيات إلى التحرير المتقدم',
      en: 'A comprehensive track to train professional journalists and digital content creators.',
      fr: 'Un parcours complet pour former des journalistes et créateurs de contenu.',
    },
    desc: {
      ar: 'تأهيل مدربين وإعلاميين محترفين يتقنون صحافة الموبايل، التحقق من المعلومات، صناعة البودكاست، وإدارة غرف الأخبار الرقمية وفق أحدث المعايير المهنية الدولية.',
      en: 'Qualifying media trainers in mobile journalism, investigative verification, podcasting, and digital newsroom management.',
      fr: 'Formation de formateurs en journalisme mobile, vérification des faits et podcasting.',
    },
    category: {
      ar: 'قسم الإعلام والاتصال / صحافة الويب',
      en: 'Media & Communication / Web Journalism',
      fr: 'Médias & Communication / Journalisme Web',
    },
    categoryBadgeText: { ar: 'إعلام واتصال', en: 'Media & Communication', fr: 'Médias & Communication' },
    coverImage: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=700&q=80',
    durationHours: 55,
    totalLessonsCount: 24,
    status: 'published',
    isAvailable: true,
    mode: { ar: 'حضوري', en: 'In-person', fr: 'Présentiel' },
    modeKey: 'onsite',
    mentor: {
      name: { ar: 'أحمد بن الشيخ', en: 'Ahmed Bencheikh', fr: 'Ahmed Bencheikh' },
      role: { ar: 'رئيس تحرير واستشاري الصحافة الرقمية', en: 'Editor-in-Chief & Media Advisor', fr: 'Rédacteur en Chef' },
      img: 'https://i.pravatar.cc/60?img=12',
    },
    trainers: [
      { id: 'tr_ab', name: { ar: 'أحمد بن الشيخ', en: 'Ahmed Bencheikh', fr: 'Ahmed Bencheikh' }, role: { ar: 'كبير مراسلي الصحافة الرقمية', en: 'Chief Digital Journalist', fr: 'Grand Reporter' }, img: 'https://i.pravatar.cc/60?img=12', isLead: true },
      { id: 'tr_sm', name: { ar: 'سارة مرابط', en: 'Sara Merabet', fr: 'Sara Merabet' }, role: { ar: 'أخصائية التحرير والتحقق الرقمي', en: 'Digital Editing Specialist', fr: 'Spécialiste Édition' }, img: 'https://i.pravatar.cc/60?img=47' },
      { id: 'tr_yh', name: { ar: 'يوسف حمدي', en: 'Youcef Hamdi', fr: 'Youcef Hamdi' }, role: { ar: 'خبير صحافة الموبايل والتصوير', en: 'Mobile Journalism Director', fr: 'Directeur MoJo' }, img: 'https://i.pravatar.cc/60?img=15' },
      { id: 'tr_lb', name: { ar: 'لينة بوزيان', en: 'Lina Bouziane', fr: 'Lina Bouziane' }, role: { ar: 'منتجة البودكاست والمحتوى الصوتي', en: 'Podcast Production Lead', fr: 'Productrice Podcast' }, img: 'https://i.pravatar.cc/60?img=32' },
    ],
    levels: {
      foundation: {
        id: 'foundation',
        title: { ar: 'مستوى التأسيس الإعلامي', en: 'Media Foundations', fr: 'Bases Médias' },
        desc: { ar: 'أخلاقيات النشر، التحرير، صحافة الموبايل وفنون البودكاست', en: 'Ethics, copywriting, mobile journalism and podcasting', fr: 'Éthique, rédaction web et mobile journalism' },
        badge: 'L1',
        modules: fndModules,
      },
    },
    finalExam: {
      title: { ar: 'الامتحان العام الشامل في الإعلام الرقمي (MED301)', en: 'Media & Journalism Track Final Exam', fr: 'Examen Final Médias' },
      passingScore: 70,
      timeMinutes: 45,
      questions: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ------------------------------------------------------------------------------------------------
// 7. Track: Creativity & Content Production (CRE401)
// ------------------------------------------------------------------------------------------------
export function buildCreativityContentTrack(): TrackDefinition {
  const fndModules: ModuleItem[] = [
    createSpecModule({
      id: 'cre_mod_01',
      num: '01',
      icon: '💡',
      gradient: 'linear-gradient(135deg, #7c3aed, #a855f7)',
      titleAr: 'التفكير الإبداعي وتوليد الأفكار الفيروسية (Ideation)',
      titleEn: 'Creative Thinking & Viral Content Ideation',
      titleFr: 'Pensée Créative et Idéation Virale',
      descAr: 'استراتيجيات العصف الذهني، صيد التريندات، وتحويل المعرفة الجافة إلى قصص مشوقة.',
      descEn: 'Brainstorming frameworks, trend analysis, and transforming dry knowledge into viral storytelling.',
      descFr: 'Idéation créative et transformation de connaissances en storytelling.',
      trainerAr: 'أحمد بن الشيخ',
      trainerEn: 'Ahmed Bencheikh',
      trainerFr: 'Ahmed Bencheikh',
      quizQuestionAr: 'ما هي المعادلة الذهبية لفكرة المحتوى الناجح؟',
      quizOptionsAr: [
        'نسخ فيديوهات الآخرين حرفياً',
        'التقاطع بين القيمة المعرفية العميقة، العرض البصري الجذاب، وتلبية حاجة حقيقية للجمهور',
        'النشر بدون تفكير في الجمهور',
        'طول مدة الفيديو لأكثر من 3 ساعات',
      ],
      quizAns: 1,
      quizExplanationAr: 'المحتوى الناجح يجمع بين المنفعة الحقيقية والأسلوب الممتع الذي يلفت الانتباه.',
    }),
    createSpecModule({
      id: 'cre_mod_02',
      num: '02',
      icon: '🎬',
      gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
      titleAr: 'كتابة السيناريو وهندسة الخطاف (Scriptwriting & Hook)',
      titleEn: 'Visual Scriptwriting & Hook Engineering',
      titleFr: 'Scénarisation et Ingénierie de l’Accroche (Hook)',
      descAr: 'كيف تقتنص انتباه المشاهد في أول 3 ثوانٍ وتحافظ على تفاعله حتى نهاية الفيديو.',
      descEn: 'Crafting high-retention hooks in the first 3 seconds and pacing short-form video scripts.',
      descFr: 'Captiver l’attention dans les 3 premières secondes et rythmer le scénario.',
      trainerAr: 'يوسف حمدي',
      trainerEn: 'Youcef Hamdi',
      trainerFr: 'Youcef Hamdi',
      quizQuestionAr: 'لماذا يعتبر "الخطاف" (Hook) في أول 3 ثوانٍ حاسماً في منصات الفيديو القصيرة؟',
      quizOptionsAr: [
        'لأنه يزيد جودة الصوت',
        'لأن خوارزميات المنصات تقيس معدل التوقف عن التمرير (Scroll Stop Rate) في الثواني الأولى وتحدد انتشار الفيديو بناءً عليه',
        'لأنه ينهي الفيديو بسرعة',
        'لا أهمية له إطلاقاً',
      ],
      quizAns: 1,
      quizExplanationAr: 'الخطاف القوي يمنع المتصفح من تجاوز الفيديو ويشجع الخوارزمية على اقتراحه لآلاف المشاهدين.',
    }),
    createSpecModule({
      id: 'cre_mod_03',
      num: '03',
      icon: '✂️',
      gradient: 'linear-gradient(135deg, #6366f1, #3b82f6)',
      titleAr: 'المونتاج الديناميكي وصناعة الريلز (Dynamic Video Editing)',
      titleEn: 'Dynamic Video Editing & Reels Production',
      titleFr: 'Montage Dynamique et Production de Reels',
      descAr: 'القص السريع، المؤثرات الصوتية B-Roll، النصوص المتحركة، وتلوين الفيديو الاحترافي.',
      descEn: 'Pacing, B-roll integration, sound design, and animated captions for short-form video.',
      descFr: 'Rythme de coupe, design sonore et sous-titrage dynamique.',
      trainerAr: 'كريم زروقي',
      trainerEn: 'Karim Zerrougui',
      trainerFr: 'Karim Zerrougui',
      quizQuestionAr: 'ما الدور الذي يلعبه التصميم الصوتي (Sound Design) في المونتاج؟',
      quizOptionsAr: [
        'يزيد من تشويش المشاهد فقط',
        'يعزز الواقعية والانغماس الحسي ويؤكد على الكلمات والمؤثرات البصرية المهمة بنسبة 50%',
        'يقلل من سرعة تصدير الفيديو',
        'يمنع ظهور الترجمة',
      ],
      quizAns: 1,
      quizExplanationAr: 'المؤثرات الصوتية الدقيقة (Swooshes, Pops, Risers) ترفع جودة الفيديو وتجعله احترافياً بامتياز.',
    }),
    createSpecModule({
      id: 'cre_mod_04',
      num: '04',
      icon: '💰',
      gradient: 'linear-gradient(135deg, #10b981, #059669)',
      titleAr: 'استراتيجيات تحقيق الدخل والرعايات (Content Monetization)',
      titleEn: 'Content Monetization & Brand Partnerships',
      titleFr: 'Monétisation et Partenariats de Marque',
      descAr: 'تحويل المشاهدات إلى مبيعات دورات واستشارات، وعقد شراكات رعاية مع العلامات التجارية.',
      descEn: 'Monetizing digital attention into course enrollments, consulting contracts, and sponsorships.',
      descFr: 'Transformer l’audience en clients et négocier des partenariats rentables.',
      trainerAr: 'عادل بلحاج',
      trainerEn: 'Adel Belhadj',
      trainerFr: 'Adel Belhadj',
      quizQuestionAr: 'ما هو نموذج الدخل الأكثر استدامة لصانع المحتوى التعليمي؟',
      quizOptionsAr: [
        'الاعتماد على إعلانات المشاهدات الزهيدة فقط',
        'بيع المنتجات المعرفية المباشرة (دورات، استشارات، عضويات، حقائب تدريبية)',
        'عدم تقديم أي خدمة للمتابعين',
        'العمل بدون أي خطة مالية',
      ],
      quizAns: 1,
      quizExplanationAr: 'المنتجات المعرفية المباشرة تمنحك استقلالية مالية كاملة وتحميك من تقلبات أرباح المنصات.',
    }),
  ];

  return {
    id: 'creativity-content',
    slug: 'creativity-content',
    specializationKey: 'creativity',
    badge: 'CRE/401',
    title: {
      ar: 'مسار تدريب المدربين في صناعة المحتوى الإبداعي',
      en: 'Trainer Training Track in Creative Content Production',
      fr: 'Parcours de formation des formateurs en Production de contenu créatif',
    },
    subtitle: {
      ar: 'اكتشف أدوات صناعة المحتوى الإبداعي من التصوير والمونتاج إلى الاستراتيجية وتحقيق الدخل',
      en: 'Discover the tools of creative content production, from filming and editing to strategy and monetization.',
      fr: 'Découvrez les outils de production de contenu créatif.',
    },
    desc: {
      ar: 'مسار إبداعي عملي للمدربين وصناع المحتوى لاحتراف سرد القصص البصرية، إنتاج الريلز الاحترافية، تصميم المنشورات الفيروسية، واستثمار الحضور الرقمي لتحقيق عائد مالي مستدام.',
      en: 'A creative hands-on track for trainers and creators to master visual storytelling, high-retention reels, viral ideation, and sustainable monetization.',
      fr: 'Parcours créatif pour maîtriser le storytelling visuel et la production de vidéos courtes.',
    },
    category: {
      ar: 'قسم الابتكار والإبداع / صناعة المحتوى',
      en: 'Innovation & Creativity / Content Creation',
      fr: 'Innovation & Créativité / Création de Contenu',
    },
    categoryBadgeText: { ar: 'ابتكار وإبداع', en: 'Innovation & Creativity', fr: 'Innovation & Créativité' },
    coverImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=700&q=80',
    durationHours: 58,
    totalLessonsCount: 24,
    status: 'published',
    isAvailable: true,
    mode: { ar: 'حضوري', en: 'In-person', fr: 'Présentiel' },
    modeKey: 'onsite',
    mentor: {
      name: { ar: 'أحمد بن الشيخ', en: 'Ahmed Bencheikh', fr: 'Ahmed Bencheikh' },
      role: { ar: 'مخرج ومستشار صناعة المحتوى الإبداعي', en: 'Creative Director & Content Strategist', fr: 'Directeur Artistique' },
      img: 'https://i.pravatar.cc/60?img=12',
    },
    trainers: [
      { id: 'tr_ab', name: { ar: 'أحمد بن الشيخ', en: 'Ahmed Bencheikh', fr: 'Ahmed Bencheikh' }, role: { ar: 'كبير مخرجي المحتوى الرقمي', en: 'Lead Creative Director', fr: 'Directeur Créatif' }, img: 'https://i.pravatar.cc/60?img=12', isLead: true },
      { id: 'tr_yh', name: { ar: 'يوسف حمدي', en: 'Youcef Hamdi', fr: 'Youcef Hamdi' }, role: { ar: 'خبير كتابة السيناريو والسرد البصري', en: 'Scriptwriter & Visual Storyteller', fr: 'Scénariste' }, img: 'https://i.pravatar.cc/60?img=15' },
      { id: 'tr_kz', name: { ar: 'كريم زروقي', en: 'Karim Zerrougui', fr: 'Karim Zerrougui' }, role: { ar: 'مهندس المونتاج والمؤثرات البصرية', en: 'Video Editing & VFX Lead', fr: 'Monteur Vidéo' }, img: 'https://i.pravatar.cc/60?img=22' },
      { id: 'tr_bl', name: { ar: 'عادل بلحاج', en: 'Adel Belhadj', fr: 'Adel Belhadj' }, role: { ar: 'مستشار تحقيق الدخل والشراكات', en: 'Monetization & Sponsorship Strategist', fr: 'Stratège Monétisation' }, img: 'https://i.pravatar.cc/60?img=8' },
    ],
    levels: {
      foundation: {
        id: 'foundation',
        title: { ar: 'مستوى تأسيس المحتوى الإبداعي', en: 'Content Foundations', fr: 'Bases de la Création' },
        desc: { ar: 'توليد الأفكار، كتابة السيناريو، المونتاج الديناميكي واستراتيجيات تحقيق الدخل', en: 'Ideation, scriptwriting, dynamic editing and monetization models', fr: 'Idéation, scénario, montage et monétisation' },
        badge: 'L1',
        modules: fndModules,
      },
    },
    finalExam: {
      title: { ar: 'الامتحان العام الشامل في صناعة المحتوى الإبداعي (CRE401)', en: 'Creative Content Track Final Exam', fr: 'Examen Final Création' },
      passingScore: 70,
      timeMinutes: 45,
      questions: [],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
